name: Release

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Cache ruby gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.OS }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-gem-

      - name: Install bundler
        run: gem install bundler -v "~>2.0" --no-document

      - name: bundle install
        run: bundle install --jobs 4 --retry 3

      - name: rake test
        run: bundle exec rake test

  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache ruby gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.OS }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-gem-

      - name: Install bundler
        run: sudo gem install bundler -v "~>2.0" --no-document

      - name: bundle install
        run: bundle install --jobs 4 --retry 3

      - name: Release gem
        uses: cadwallion/publish-rubygems-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
          RELEASE_COMMAND: bundle exec rake release
