name: Release

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Cache ruby gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.OS }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-gem-

      - name: Install bundler
        run: gem install bundler -v "~>2.0" --no-document

      - name: bundle install
        run: bundle install --jobs 4 --retry 3

      - name: rake test
        run: bundle exec rake test

      - name: Set git identity
        run: |
          git config user.email "mike@patientdiscovery.com"
          git config user.name "Michael Keirnan"

      - name: Setup rubygems and Github credentials
        run: |
          mkdir -p ~/.gem
          cat << EOF > ~/.gem/credentials
          ---
          :github: Bearer ${{ secrets.GITHUB_TOKEN }}
          :rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}
          EOF

          chmod 0600 ~/.gem/credentials

      - name: Release
        run: bundle exec rake release
